# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peminjaman.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'peminjaman.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10peminjaman.proto\x12\npeminjaman\",\n\x0f\x43heckoutRequest\x12\x0b\n\x03nim\x18\x01 \x01(\t\x12\x0c\n\x04isbn\x18\x02 \x01(\t\"1\n\x10\x43heckoutResponse\x12\x0e\n\x06sukses\x18\x01 \x01(\x08\x12\r\n\x05pesan\x18\x02 \x01(\t2`\n\x11PeminjamanService\x12K\n\x0c\x43heckoutBuku\x12\x1b.peminjaman.CheckoutRequest\x1a\x1c.peminjaman.CheckoutResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peminjaman_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKOUTREQUEST']._serialized_start=32
  _globals['_CHECKOUTREQUEST']._serialized_end=76
  _globals['_CHECKOUTRESPONSE']._serialized_start=78
  _globals['_CHECKOUTRESPONSE']._serialized_end=127
  _globals['_PEMINJAMANSERVICE']._serialized_start=129
  _globals['_PEMINJAMANSERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
