# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import peminjaman_pb2 as peminjaman__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in peminjaman_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeminjamanServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckoutBuku = channel.unary_unary(
                '/peminjaman.PeminjamanService/CheckoutBuku',
                request_serializer=peminjaman__pb2.CheckoutRequest.SerializeToString,
                response_deserializer=peminjaman__pb2.CheckoutResponse.FromString,
                _registered_method=True)


class PeminjamanServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckoutBuku(self, request, context):
        """Fungsi yang akan dipanggil oleh Kios saat mahasiswa scan buku
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeminjamanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckoutBuku': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckoutBuku,
                    request_deserializer=peminjaman__pb2.CheckoutRequest.FromString,
                    response_serializer=peminjaman__pb2.CheckoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'peminjaman.PeminjamanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('peminjaman.PeminjamanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeminjamanService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckoutBuku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peminjaman.PeminjamanService/CheckoutBuku',
            peminjaman__pb2.CheckoutRequest.SerializeToString,
            peminjaman__pb2.CheckoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
