# Generated by Django 6.1.1 on 2026-09-28 07:34

import api_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('stok_tersedia', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['judul'], name='idx_judul_btree'), models.Index(fields=['penulis'], name='idx_penulis_btree')],
            },
        ),
        migrations.CreateModel(
            name='TransaksiPeminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tenggat_kembali', models.DateTimeField(default=api_app.models.tenggat_default)),
                ('tanggal_dikembalikan', models.DateTimeField(blank=True, null=True)),
                ('denda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DIPINJAM', 'Dipinjam'), ('DIKEMBALIKAN', 'Dikembalikan'), ('TERLAMBAT', 'Terlambat')], default='DIPINJAM', max_length=20)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.buku')),
            ],
            options={
                'indexes': [models.Index(fields=['anggota', 'status'], name='idx_anggota_status')],
            },
        ),
    ]
